name: Github Action 실행시켜보기

on:
    push:
        branches:
            - main
jobs:
    My-Deploy-jobs:
        runs-on: ubuntu-latest

        steps:
            - name: Hello World 출력하기
            run: echo "Hello World"