name: Deploy To S3 And Invalidate Cloudfront

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Github repository 파일 불러오기
              uses: actions/checkout@v4

            - name: repository 파일 출력하기
              run: ls